version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ~/gitrepo/docker-study/recipe-01/html:/var/www/myapp
      - ~/gitrepo/docker-study/recipe-01/docker/sec.conf:/etc/nginx/conf.d/sec.conf
      - ~/gitrepo/docker-study/recipe-01/docker/site.conf:/etc/nginx/conf.d/site.conf
      - ~/gitrepo/docker-study/recipe-01/docker/global.conf:/etc/nginx/conf.d/global.conf
